# Docker Compose override for NVIDIA GPU support (Legacy syntax)
# Use this file if docker-compose.gpu.yaml fails with "could not select device driver nvidia" error
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.gpu-legacy.yaml up
#
# PREREQUISITES:
# 1. Install NVIDIA Container Runtime: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html
# 2. Add nvidia runtime to /etc/docker/daemon.json:
#    {
#      "runtimes": {
#        "nvidia": {
#          "path": "nvidia-container-runtime",
#          "runtimeArgs": []
#        }
#      }
#    }
# 3. Restart Docker daemon: sudo systemctl restart docker
# 4. Verify with: docker run --rm --runtime=nvidia nvidia/cuda:11.0-base nvidia-smi

version: "3.8"

services:
  app:
    # Legacy GPU syntax (compatible with older Docker versions)
    runtime: nvidia
    
    environment:
      # Ensure NVIDIA GPU environment variables are set
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      # Force GPU usage in the application
      ENABLE_GPU: "true"
      # CUDA specific optimizations
      CUDA_VISIBLE_DEVICES: all
      CUDA_LAUNCH_BLOCKING: "0" 