model = ["F5TTS", "tts_models/multilingual/multi-dataset/xtts_v2" ,"Zyphra/Zonos-v0.1-transformer"]
ref_audio = "/home/styx/Videos/VoiceClone/Input Audio/Oppenheimer Demo Clip.wav"
ref_text = "of course the initial discovery and its interpretation in early 1939 attracted everybody's interest."
gen_text = "My name is Robert J Oppenheimer and welcome to the Titans of Energy statue exhibit at the Oak Ridge National Laboratory."
clean_audio=true
remove_silence = true
enhance_audio = true
preprocessing_order = ['enhance', 'remove_silence', 'clean']
output_dir = "Test5.6"
